require('dotenv').config();
const express=require('express'),crypto=require('crypto'),path=require('path');
const {Pool}=require('pg');
const app=express(), pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:undefined});
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type,x-admin-password');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use(express.json({limit:'3mb',verify:(req,res,buf)=>{req.rawBody=buf.toString('utf8')}}));app.use(express.static('public'));
const SQUARE_VERSION='2026-09-16';
const squareHost=()=>process.env.SQUARE_ENV==='production'?'https://connect.squareup.com':'https://connect.squareupsandbox.com';
async function squareFetch(endpoint,opts={}){if(!process.env.SQUARE_ACCESS_TOKEN)throw Error('Square is not configured');let r=await fetch(squareHost()+endpoint,{...opts,headers:{Authorization:`Bearer ${process.env.SQUARE_ACCESS_TOKEN}`,'Content-Type':'application/json','Square-Version':SQUARE_VERSION,...(opts.headers||{})}});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.errors?.[0]?.detail||`Square request failed (${r.status})`);return d}

const admin=(req,res,next)=>{if(req.headers['x-admin-password']!==(process.env.ADMIN_PASSWORD||''))return res.status(401).json({error:'Unauthorized'});next()};
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,price_cents INTEGER NOT NULL,category TEXT NOT NULL,description TEXT DEFAULT '',stock INTEGER NOT NULL DEFAULT 0,badge TEXT DEFAULT '',image TEXT DEFAULT '',active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,created_at TIMESTAMPTZ DEFAULT NOW(),name TEXT NOT NULL,email TEXT NOT NULL,fulfillment TEXT NOT NULL,total_cents INTEGER NOT NULL,status TEXT NOT NULL,payment_id TEXT,items JSONB NOT NULL); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); ALTER TABLE orders ADD COLUMN IF NOT EXISTS phone TEXT; ALTER TABLE orders ADD COLUMN IF NOT EXISTS dropoff_location TEXT; ALTER TABLE orders ADD COLUMN IF NOT EXISTS square_order_id TEXT; ALTER TABLE products ADD COLUMN IF NOT EXISTS square_item_id TEXT; ALTER TABLE products ADD COLUMN IF NOT EXISTS square_variation_id TEXT; ALTER TABLE products ADD COLUMN IF NOT EXISTS square_synced BOOLEAN DEFAULT FALSE; ALTER TABLE products ADD COLUMN IF NOT EXISTS square_updated_at TIMESTAMPTZ; CREATE UNIQUE INDEX IF NOT EXISTS products_square_variation_unique ON products(square_variation_id) WHERE square_variation_id IS NOT NULL;`)}
const productOut=r=>({id:r.id,name:r.name,price:r.price_cents/100,category:r.category,description:r.description,stock:r.stock,badge:r.badge,image:r.image,active:r.active,squareLinked:!!r.square_variation_id,squareItemId:r.square_item_id||null,squareVariationId:r.square_variation_id||null});
async function syncSquareCatalog(){
  if(!process.env.SQUARE_ACCESS_TOKEN||!process.env.SQUARE_LOCATION_ID)throw Error('Square credentials are missing');
  let objects=[],cursor='';
  do{let q='/v2/catalog/list?types=ITEM,IMAGE'+(cursor?'&cursor='+encodeURIComponent(cursor):'');let d=await squareFetch(q);objects.push(...(d.objects||[]));cursor=d.cursor||''}while(cursor);
  let images=new Map(objects.filter(o=>o.type==='IMAGE').map(o=>[o.id,o.image_data?.url||'']));
  let items=objects.filter(o=>o.type==='ITEM'&&!o.is_deleted);let variations=[];
  for(let item of items){let data=item.item_data||{};for(let v of data.variations||[]){if(v.is_deleted)continue;let vd=v.item_variation_data||{};if(v.present_at_location_ids&&!v.present_at_location_ids.includes(process.env.SQUARE_LOCATION_ID))continue;if(v.absent_at_location_ids?.includes(process.env.SQUARE_LOCATION_ID))continue;let price=vd.price_money?.amount;if(price==null)continue;let imageId=(vd.image_ids||[])[0]||(data.image_ids||[])[0]||null;let vn=(vd.name||'').trim();let name=(vn&& !/^regular$/i.test(vn))?`${data.name} — ${vn}`:data.name;variations.push({itemId:item.id,variationId:v.id,name:name||'Square item',price:Number(price),description:data.description_plaintext||data.description||'',image:imageId?images.get(imageId)||'':'',updatedAt:v.updated_at||item.updated_at||new Date().toISOString()})}}
  let ids=variations.map(v=>v.variationId),stock=new Map();
  if(ids.length){for(let i=0;i<ids.length;i+=1000){let d=await squareFetch('/v2/inventory/counts/batch-retrieve',{method:'POST',body:JSON.stringify({catalog_object_ids:ids.slice(i,i+1000),location_ids:[process.env.SQUARE_LOCATION_ID],states:['IN_STOCK']})});for(let c of d.counts||[])stock.set(c.catalog_object_id,Math.max(0,Math.floor(Number(c.quantity)||0)))}}
  let seen=[];
  for(let v of variations){seen.push(v.variationId);await pool.query(`INSERT INTO products(id,name,price_cents,category,description,stock,badge,image,active,square_item_id,square_variation_id,square_synced,square_updated_at) VALUES($1,$2,$3,'squishy',$4,$5,'',$6,TRUE,$7,$8,TRUE,$9) ON CONFLICT(square_variation_id) WHERE square_variation_id IS NOT NULL DO UPDATE SET name=EXCLUDED.name,price_cents=EXCLUDED.price_cents,description=EXCLUDED.description,stock=EXCLUDED.stock,image=EXCLUDED.image,active=TRUE,square_item_id=EXCLUDED.square_item_id,square_synced=TRUE,square_updated_at=EXCLUDED.square_updated_at`,['sq-'+v.variationId,v.name,v.price,v.description,stock.get(v.variationId)||0,v.image,v.itemId,v.variationId,v.updatedAt])}
  if(seen.length)await pool.query('UPDATE products SET active=FALSE WHERE square_synced=TRUE AND NOT (square_variation_id=ANY($1::text[]))',[seen]);else await pool.query('UPDATE products SET active=FALSE WHERE square_synced=TRUE');
  return {items:variations.length};
}
async function syncSquareInventory(){let {rows}=await pool.query('SELECT square_variation_id FROM products WHERE square_synced=TRUE AND square_variation_id IS NOT NULL');let ids=rows.map(r=>r.square_variation_id);if(!ids.length)return {items:0};for(let i=0;i<ids.length;i+=1000){let d=await squareFetch('/v2/inventory/counts/batch-retrieve',{method:'POST',body:JSON.stringify({catalog_object_ids:ids.slice(i,i+1000),location_ids:[process.env.SQUARE_LOCATION_ID],states:['IN_STOCK']})});let got=new Set();for(let c of d.counts||[]){got.add(c.catalog_object_id);await pool.query('UPDATE products SET stock=$2 WHERE square_variation_id=$1',[c.catalog_object_id,Math.max(0,Math.floor(Number(c.quantity)||0))])}for(let id of ids.slice(i,i+1000))if(!got.has(id))await pool.query('UPDATE products SET stock=0 WHERE square_variation_id=$1',[id])}return {items:ids.length}}

app.get('/api/products',async(req,res)=>{try{let {rows}=await pool.query('SELECT * FROM products WHERE active=TRUE ORDER BY created_at DESC');res.json(rows.map(productOut))}catch(e){res.status(500).json({error:'Database unavailable'})}});
app.get('/api/config',async(req,res)=>{res.json({appId:process.env.SQUARE_APP_ID||'',locationId:process.env.SQUARE_LOCATION_ID||'',environment:process.env.SQUARE_ENV||'sandbox',dropoffFee:5})});
app.get('/api/admin/summary',admin,async(req,res)=>{let rr=await pool.query("SELECT value FROM settings WHERE key='sales_reset_at'");let resetAt=rr.rows[0]?.value||'1970-01-01T00:00:00.000Z';let p=await pool.query('SELECT COUNT(*)::int AS products FROM products WHERE active=TRUE');let o=await pool.query('SELECT COUNT(*)::int AS orders FROM orders');let rev=await pool.query("SELECT COALESCE(SUM(total_cents),0)::bigint AS cents FROM orders WHERE status IN ('PAID','COMPLETED') AND created_at >= $1",[resetAt]);res.json({products:p.rows[0].products,orders:o.rows[0].orders,paidSales:Number(rev.rows[0].cents)/100,salesResetAt:resetAt})});
app.get('/api/admin/products',admin,async(req,res)=>{let {rows}=await pool.query('SELECT * FROM products ORDER BY created_at DESC');res.json(rows.map(productOut))});
app.post('/api/admin/products',admin,async(req,res)=>{try{let p=req.body,id=crypto.randomUUID();let q=await pool.query('INSERT INTO products(id,name,price_cents,category,description,stock,badge,image) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id,p.name,Math.round(Number(p.price)*100),p.category,p.description||'',Math.max(0,Number(p.stock)||0),p.badge||'',p.image||'']);res.json(productOut(q.rows[0]))}catch(e){res.status(400).json({error:'Could not save product'})}});
app.put('/api/admin/products/:id',admin,async(req,res)=>{try{let p=req.body;let q=await pool.query('UPDATE products SET name=$2,price_cents=$3,category=$4,description=$5,stock=$6,badge=$7,image=$8 WHERE id=$1 RETURNING *',[req.params.id,p.name,Math.round(Number(p.price)*100),p.category,p.description||'',Math.max(0,Number(p.stock)||0),p.badge||'',p.image||'']);res.json(productOut(q.rows[0]))}catch(e){res.status(400).json({error:'Could not update product'})}});
app.delete('/api/admin/products/:id',admin,async(req,res)=>{await pool.query('DELETE FROM products WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.get('/api/orders/:id',async(req,res)=>{try{let email=String(req.query.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'Enter the email used for the order'});let {rows}=await pool.query('SELECT id,created_at,name,email,phone,fulfillment,dropoff_location,total_cents,status,items FROM orders WHERE id=$1 AND LOWER(email)=$2',[req.params.id,email]);if(!rows.length)return res.status(404).json({error:'Order not found. Check the order number and email.'});let o=rows[0];res.json({id:o.id,createdAt:o.created_at,name:o.name,fulfillment:o.fulfillment,dropoffLocation:o.dropoff_location,total:o.total_cents/100,status:o.status,items:o.items||[]})}catch(e){res.status(500).json({error:'Could not load order'})}});
app.get('/api/admin/orders',admin,async(req,res)=>{let {rows}=await pool.query('SELECT * FROM orders ORDER BY created_at DESC');res.json(rows.map(o=>({...o,total:o.total_cents/100,createdAt:o.created_at})))});
app.put('/api/admin/orders/:id',admin,async(req,res)=>{let allowed=['PAID','ORDERED','ARRIVED','PREPARING','READY','OUT FOR DROP-OFF','COMPLETED','CANCELED','DEMO'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});await pool.query('UPDATE orders SET status=$2 WHERE id=$1',[req.params.id,req.body.status]);res.json({ok:true})});
app.post('/api/admin/square-sync',admin,async(req,res)=>{try{let result=await syncSquareCatalog();res.json({ok:true,...result})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/square/webhook',async(req,res)=>{try{let key=process.env.SQUARE_WEBHOOK_SIGNATURE_KEY;if(!key)return res.status(503).send('Webhook signature key not configured');let sig=String(req.headers['x-square-hmacsha256-signature']||'');let notificationUrl=process.env.SQUARE_WEBHOOK_URL||`https://${req.get('host')}/api/square/webhook`;let expected=crypto.createHmac('sha256',key).update(notificationUrl+(req.rawBody||''),'utf8').digest('base64');let a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(403).send('Invalid signature');
  // Square requires a quick 2xx. Update directly from the inventory payload after acknowledging it.
  res.sendStatus(200);let type=req.body?.type;
  if(type==='catalog.version.updated'){syncSquareCatalog().catch(e=>console.error('Square catalog webhook sync failed',e));return}
  if(type==='inventory.count.updated'){
    let counts=req.body?.data?.object?.inventory_counts||[];
    Promise.all(counts.filter(c=>c.location_id===process.env.SQUARE_LOCATION_ID&&c.state==='IN_STOCK').map(c=>pool.query('UPDATE products SET stock=$2,square_updated_at=NOW() WHERE square_variation_id=$1',[c.catalog_object_id,Math.max(0,Math.floor(Number(c.quantity)||0))])))
      .catch(e=>console.error('Square inventory webhook update failed',e));
  }
}catch(e){console.error(e);if(!res.headersSent)res.sendStatus(500)}});
app.post('/api/checkout',async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');let {sourceId,name,email,phone,fulfillment,dropoffLocation,items}=req.body;if(!name||!email||!phone||!Array.isArray(items)||!items.length)throw Error('Missing checkout information');if(!['Local pickup','Local drop-off'].includes(fulfillment))throw Error('Choose a valid fulfillment option');if(fulfillment==='Local drop-off'&&!dropoffLocation)throw Error('Drop-off location is required');let ids=items.map(i=>i.id),{rows}=await client.query('SELECT * FROM products WHERE id=ANY($1::text[]) FOR UPDATE',[ids]);let map=new Map(rows.map(r=>[r.id,r])),normalized=[],cents=0;for(let i of items){let p=map.get(i.id),qty=Math.max(1,Number(i.qty)||1);if(!p||!p.active)throw Error('A product is no longer available');if(qty>p.stock)throw Error(`${p.name} does not have enough stock`);normalized.push({id:p.id,name:p.name,price:p.price_cents/100,qty,squareVariationId:p.square_variation_id||null});cents+=p.price_cents*qty}let dropFee=fulfillment==='Local drop-off'?500:0;if(dropFee)cents+=dropFee;let processingFee=Math.round(cents*0.03);cents+=processingFee
let paymentId=null,squareOrderId=null,demo=(process.env.SQUARE_ENV||'sandbox')!=='production'&&!process.env.SQUARE_ACCESS_TOKEN;
if(!demo){let line_items=normalized.map(i=>i.squareVariationId?{catalog_object_id:i.squareVariationId,quantity:String(i.qty)}:{name:i.name,quantity:String(i.qty),base_price_money:{amount:Math.round(i.price*100),currency:'USD'}});if(dropFee)line_items.push({name:'Local Drop-Off',quantity:'1',base_price_money:{amount:dropFee,currency:'USD'}});if(processingFee)line_items.push({name:'Processing',quantity:'1',base_price_money:{amount:processingFee,currency:'USD'}});let od=await squareFetch('/v2/orders',{method:'POST',body:JSON.stringify({idempotency_key:crypto.randomUUID(),order:{location_id:process.env.SQUARE_LOCATION_ID,reference_id:'MIMI-'+Date.now(),line_items}})});squareOrderId=od.order?.id;if(!squareOrderId)throw Error('Square order could not be created');let pr=await squareFetch('/v2/payments',{method:'POST',body:JSON.stringify({source_id:sourceId,idempotency_key:crypto.randomUUID(),amount_money:{amount:cents,currency:'USD'},autocomplete:true,location_id:process.env.SQUARE_LOCATION_ID,order_id:squareOrderId,note:`Mimi's Squishies order for ${name}`})});paymentId=pr.payment.id}
let id='MS-'+Date.now().toString().slice(-8);for(let i of normalized)await client.query('UPDATE products SET stock=GREATEST(0,stock-$2) WHERE id=$1',[i.id,i.qty]);await client.query('INSERT INTO orders(id,name,email,phone,fulfillment,dropoff_location,total_cents,status,payment_id,square_order_id,items) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,name,email,phone,fulfillment,dropoffLocation||null,cents,demo?'DEMO':'PAID',paymentId,squareOrderId,JSON.stringify(normalized)]);await client.query('COMMIT');if(!demo)syncSquareInventory().catch(console.error);res.json({ok:true,demo,order:{id,total:cents/100,status:demo?'DEMO':'PAID'}})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message||'Checkout failed'})}finally{client.release()}});
app.get('/api/admin/settings',admin,async(req,res)=>{res.json({dropoffFee:5})});
app.put('/api/admin/settings',admin,async(req,res)=>{res.json({ok:true,dropoffFee:5})});

app.post('/api/admin/reset-sales',admin,async(req,res)=>{let now=new Date().toISOString();await pool.query("INSERT INTO settings(key,value) VALUES('sales_reset_at',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[now]);res.json({ok:true,salesResetAt:now})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('Mimi shop ready'))).catch(e=>{console.error('DB init failed',e);process.exit(1)});